name: lint-&-Push-to-EC2

on:
  workflow_dispatch:
  push:
    branches:
      - main
      
jobs:
  pylint:      
#         build:
          name: pylint
          runs-on: ubuntu-latest
          strategy:
            matrix:
              python-version: ["3.8", "3.9", "3.10"]
          steps:
          - uses: actions/checkout@v3
          - name: Set up Python ${{ matrix.python-version }}
            uses: actions/setup-python@v3
            with:
              python-version: ${{ matrix.python-version }}
          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              pip install pylint
          - name: Analysing the code with pylint
            run: |
              pylint --fail-under=7 $(git ls-files '*.py')
              
  EC2:
#               deploy:
#                 name: Deploy to EC2
          if: always() && needs.pylint.result != failure()
          runs-on: ubuntu-latest
          steps:
            - name: Checkout the files
              uses: actions/checkout@v3

            - name: Deploy to Server 1
              uses: easingthemes/ssh-deploy@main
              env:
                SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
                REMOTE_HOST: ${{ secrets.HOST_DNS }}
                REMOTE_USER: ${{ secrets.USERNAME }}
                TARGET: ${{ secrets.TARGET_DIR }}

